dtb-$(CONFIG_ARCH_EXYNOS7) += exynos7-espresso.dtb

dtb-$(CONFIG_SOC_EXYNOS8895) += exynos8895-greatlte_eur_open_00.dtb exynos8895-greatlte_eur_open_01.dtb exynos8895-greatlte_eur_open_02.dtb exynos8895-greatlte_eur_open_06.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
